#! /bin/bash

. $(dirname `readlink -f $0`)/common.sh

if [ -z "${eclipse_home}" ]; then
  setup_home
fi

if [ -z "${p2qJar}" ]; then
  setup_jar
fi

app=com.github.utils4e.app.JDTQueryApp

java -classpath ${osgiJar}:${p2qJar}:${slf4jApiJar} ${app} ${eclipse_home} ${p2qJar}:${fpp2Jar} ${@}
